# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Sonar-Coveralls

on:
  push:
    branches:
      - master
      - "rel/*"
      - parallel_coveralls
    paths-ignore:
      - "docs/**"
      - 'site/**'
  pull_request:
    branches:
      - master
      - "rel/*"
    paths-ignore:
      - "docs/**"
      - 'site/**'
  # allow manually run the action:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3
  PR_NUMBER: ${{ github.event.number }}

jobs:
  coveralls-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == 'apache/iotdb' || github.event_name == 'push'
    strategy:
      matrix:
        task:
          - datanode
          - others

    steps:
      - uses: actions/checkout@v3
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Test datanode
        if: ${{ matrix.task == 'datanode'}}
        run: mvn -B clean compile test -pl iotdb-core/datanode -am -DskipTests=true -Diotdb.test.only=true -Dtest.port.closed=true -Pcode-coverage
      - name: Test other
        if: ${{ matrix.task == 'others'}}
        run: mvn -B clean compile test -pl distribution,iotdb-client/cli,iotdb-client/session,iotdb-client/jdbc -am -Diotdb.test.skip=true -Dtest.port.closed=true -Pcode-coverage
      - name: Merge report
        run: mvn -B post-integration-test -Pcode-coverage -pl code-coverage
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALL_TOKEN }}
          file: code-coverage/target/jacoco-merged-reports/jacoco.xml
          flag-name: run-${{ matrix.task }}
          parallel: true

  coveralls-report:
    needs: coveralls-test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALL_TOKEN }}
          parallel-finished: true
          carryforward: "run-datanode,run-others"

  sonar:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == 'apache/iotdb' || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: SonarCloud Report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: |
          mvn -B verify sonar:sonar \
          -Dsonar.organization=apache \
          -Dsonar.projectKey=apache_incubator-iotdb \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }} \
          -DskipTests -pl '!distribution,!integration-test' -am
